# Generated by Django 5.1.6 on 2025-02-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_number',
            field=models.CharField(default='TBD', max_length=10),
        ),
    ]
