# Generated by Django 5.1.6 on 2025-02-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_booking_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
