# Generated by Django 5.1.6 on 2025-02-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_room_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
