# Generated by Django 5.1.6 on 2025-02-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_booking_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_number',
        ),
    ]
