# Generated by Django 5.1.6 on 2025-03-15 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_fooditem_description_alter_order_food_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='owner',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='owners',
            field=models.ManyToManyField(related_name='managed_restaurants', to=settings.AUTH_USER_MODEL),
        ),
    ]
